### ISSUE TITLE
DB target 설정

### ISSUE THREAD

**Issue by sangwon21** [connect-foundation/2019-08#1]
**Description**
> 사용할 DB 종류를 정한다. 

**Sub Task**

- [ ] 다뤄야할 데이터의 성질에 맞춰 알맞은 데이터베이스를 선택한다. (예. RDBMS vs NO-SQL)

**Comment by raccoonback** [comment]
## 데이터 베이스는 무엇을 쓸 것인가?

###  몽고디비
- 비정형 데이터 처리에 유리하다.

### Mysql
- 인덱스를 이용하면, 조회가 빠를수 있다.

### 대안
- 우선 Mysql을 사용하고, 추후 성능 문제가 있을 시 고민해볼 것??
