### ISSUE TITLE
채널을 생성했을 때, 채널 생성 요청을 서버에 AJAX 요청을 보낸다.

### ISSUE THREAD

**Issue by kyungrae** [connect-foundation/2019-08#10]
**Description**

> 채널의 이름, 공개/비공개 속성을 json 형식으로 서버에 전송하고 채널 생성 결과를 확인한다.

**(option)Sub Task**

- [ ] 채널 생성에 필요한 API 통신 규칙 이슈를 생성한다.

**Comment by raccoonback** [comment]
### Feature List
- [ ] Channel 객체를 구성한다.
- [ ] 입력받은 채널 정보를 검증한다.
- [ ] 서버에 채널 정보를 전송한다.
- [ ] 서버로 부터 201 상태 코드를 응답받은 경우, 초대 정보를 입력받는 컴포넌트로 이동한다.
- [ ] 서버로 부터 400 상태 코드를 응답받은 경우, 입력한 채널정보가 잘못된 것을 알려준다.

### Channel 객체
: 채널 정보를 가지는 모델

#### 상태
- name : 채널의 이름
- description: 채널 설명
- visibility: 공개/비공개 여부

**Comment by raccoonback** [comment]
Closed By #27

**Comment by raccoonback** [comment]
Closed By #27
