### ISSUE TITLE
회원가입 페이지 이상해요

### ISSUE THREAD

**Issue by ocy1011** [connect-foundation/2019-08#124]
![K-054](https://user-images.githubusercontent.com/34512577/70299136-641b4c80-1837-11ea-884f-bcc64cc54842.png)

## 상황
1. 아이디 중복검사를 하면 404에러
2. 화면 줄이면 엘리먼트들이 축소되면서 깨져 보입니다.

**Comment by kyungrae** [comment]
감사합니다. 배포시 환경변수와 로직적으로 문제가 있는것 같습니다. 빠르게 수정하겠습니다.
