### ISSUE TITLE
[bug] 이미지가 안보여요

### ISSUE THREAD

**Issue by changicho** [connect-foundation/2019-08#126]
탬플릿대로는 못하겠네요

![image](https://user-images.githubusercontent.com/38618187/70300940-443a5780-183c-11ea-8ac8-0cdbbf81d85e.png)

이미지가 안보여요!!

**Comment by kyungrae** [comment]
아직 파일 업로드를 구현하지 못해 이미지가 깨지고 있습니다. 빠르게 구현하겠습니다. 감사합니다.
