### ISSUE TITLE
Snug 사용 설명서 이미지 gif

### ISSUE THREAD

**Issue by GiPyoo** [connect-foundation/2019-08#229]
![회원가입](https://user-images.githubusercontent.com/44811887/71326064-1b52db80-2539-11ea-8da5-56aab6d9cbd3.gif)

**Comment by GiPyoo** [comment]
![스너그 생성](https://user-images.githubusercontent.com/44811887/71326155-4e499f00-253a-11ea-99b0-b4260d974711.gif)

**Comment by GiPyoo** [comment]
![초대](https://user-images.githubusercontent.com/44811887/71326204-024b2a00-253b-11ea-9b32-04f5bc6f84fb.gif)

**Comment by sangwon21** [comment]
👍
