### ISSUE TITLE
DB 세팅 및 TypeOrm 적용

### ISSUE THREAD

**Issue by sangwon21** [connect-foundation/2019-08#3]
**Description**
> 사용하기로 결정한 DB를 개발자 로컬 환경에 설정한다. 더불어 원격 서버에도 DB를 설정한다.

### DB 조사
- db: mysql
- version: 8
- character-set: [utf8mb4](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html) => 가변 4byte(이모지 지원)
- collation: [utf8mb4_bin](https://dev.mysql.com/doc/refman/8.0/en/charset-collation-names.html) => 정렬하기 위한 비교 방식

https://stackoverflow.com/questions/37364618/utf8mb4-unicode-ci-vs-utf8mb4-bin

**Comment by raccoonback** [comment]
`synchronize: true` 설정은 production 환경에서 db를 변경할 수 있기 때문에  권장하지 않는다.

**Comment by raccoonback** [comment]
https://github.com/Kononnable/typeorm-model-generator

**Comment by raccoonback** [comment]
새로운 모델 생성시, npx typeorm migration:create -n 마이그레이션명

**Comment by raccoonback** [comment]
BaseEntity 상속받아 Entity를 정의하면 Active Record pattern 으로 Repository or EntityManager 을 사용할 필요가 없다.

Active Record pattern VS Data Mapper

**Comment by raccoonback** [comment]
subscriber 은 엔터티 에서 발생한 event 대해서 처리를 할 수 있다.

https://typeorm.io/#/listeners-and-subscribers

**Comment by raccoonback** [comment]
### Embedded Entities
=> composition(조합?)

### Entity Inheritance
=> 상속

**Comment by raccoonback** [comment]
### tree structures 

https://typeorm.io/#/tree-entities

**Comment by raccoonback** [comment]
* 로컬 환경에서는 console 에 로깅을 나타내며, 지속적으로 DB 와 스키마를 동기화한다.
 * development server 환경에서는 많은 정보를 로그에 담고, CLI 를 통해서만 DB 와 스키마를 동기화하도록 제한한다.
 * production server 환경에서는 운여에서 발생할 수 있는 정보만 로그에 담고, CLI 를 통해서만 DB 와 스키마를 동기화하도록 제한한다.

**Comment by raccoonback** [comment]
### SQL Injection

- https://github.com/typeorm/typeorm/issues/3696
- https://github.com/typeorm/typeorm/issues/3740
- https://github.com/typeorm/typeorm/issues/3862
