### ISSUE TITLE
[질문] socket에 의한 데이터 송수신에 관해서

### ISSUE THREAD

**Issue by GiPyoo** [connect-foundation/2019-08#32]
**About Issue(s)**
- #19 #13 
**Code and(or) Your Effort**
제가 생각하는모습은 sub data의 이미지와 같습니다.

**Question of this problem**
1. 1번안과 2번안 중 무엇이 맞는지 모르겠습니다. @kyungrae 

**sub data**
![KakaoTalk_Photo_2019-11-19-14-40-42](https://user-images.githubusercontent.com/44811887/69119651-9a886600-0ada-11ea-9493-f62f8e0d1003.jpeg)

**Comment by kyungrae** [comment]
1번이 더 좋은 방법이라고 생각합니다. 

2번의 경우 서버에서 응답이 오면 server logic 제대로 됬음을 확인할 수 있지만 socket 로직이 제대로 작동하고 있는지 모르기 때문에 socket 응답을 받고 렌더링하는게 좋은 방법이라고 생각합니다.

**Comment by GiPyoo** [comment]
@kyungrae 감사합니다
