### ISSUE TITLE
Entity 의 타입과 컨텍스트 타입의 불일치 문제

### ISSUE THREAD

**Issue by GiPyoo** [connect-foundation/2019-08#64]
같은 채널인데 서로 다른 의미를 가진 엔티티 입니다 통일이 필요합니다.

@sangwon21 @raccoonback

**Comment by sangwon21** [comment]
privacy visibility문제인가요?

**Comment by GiPyoo** [comment]
> privacy visibility문제인가요?

그외 스트링 헬퍼, 기타 다양한 것들이 너무 많이 나열 되어있어서 손등 댈수가 없을 것 같습니다. 두분이 설계하신거라 두 분의 상의가 필요합니다. @sangwon21 @raccoonback
