### ISSUE TITLE
서버 소켓 구현하기

### ISSUE THREAD

**Issue by GiPyoo** [connect-foundation/2019-08#68]
**Description**

> 서버에서 소켓을 연결하여 클라이언트와 직접 소통할 수 있도록 하였다.

**(option)Sub Task**

- [x] 서버 커넥션 구현
- [x] 룸에 들어가는 소켓 이벤트 구현
- [x] 포스트 디비에 post 인스턴스가 저장되면  되면 저장된 포스트를 그 룸에 뿌려주는 소켓 구현

**예상작업시간**
- 1 MD

**Comment by kyungrae** [comment]
#70 

### Event name
`newPost`

### Data 
```javascript
{
  message: // api 결과 메시지
  payload: {
      // 새로 생성된 channel 정보
      // 중복된 채널명 존재하는 경우, 빈 상태로 전달
  }
}
```
